
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CURLBRACKETSLEFT = 33;
  public static final int BRACKETSRIGHT = 32;
  public static final int MULT = 23;
  public static final int PARENTHLEFT = 29;
  public static final int CURLBRACKETSRIGHT = 34;
  public static final int INT = 7;
  public static final int MINUS = 22;
  public static final int NUMBER_LIT = 37;
  public static final int STATIC = 5;
  public static final int PARENTHRIGHT = 30;
  public static final int NOT = 24;
  public static final int SEMICOLON = 26;
  public static final int AND = 19;
  public static final int LT = 20;
  public static final int COMMA = 27;
  public static final int CLASS = 2;
  public static final int PLUS = 21;
  public static final int ASSIGN = 25;
  public static final int MAIN = 18;
  public static final int IF = 11;
  public static final int THIS = 16;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 13;
  public static final int TRUE = 15;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int BRACKETSLEFT = 31;
  public static final int VOID = 6;
  public static final int ELSE = 12;
  public static final int WHILE = 10;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 4;
  public static final int SYSO = 35;
  public static final int STRING = 8;
  public static final int FALSE = 14;
  public static final int LENGTH = 36;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "EXTENDS",
  "STATIC",
  "VOID",
  "INT",
  "STRING",
  "BOOLEAN",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "FALSE",
  "TRUE",
  "THIS",
  "NEW",
  "MAIN",
  "AND",
  "LT",
  "PLUS",
  "MINUS",
  "MULT",
  "NOT",
  "ASSIGN",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "PARENTHLEFT",
  "PARENTHRIGHT",
  "BRACKETSLEFT",
  "BRACKETSRIGHT",
  "CURLBRACKETSLEFT",
  "CURLBRACKETSRIGHT",
  "SYSO",
  "LENGTH",
  "NUMBER_LIT",
  "IDENTIFIER"
  };
}

